[ui]
# Hide the menu and footer
hideTopBar = true
hideSidebarNav = true

[browser]
# Don't gather usage stats
gatherUsageStats = false

[server]
# Server configuration
enableCORS = false
enableXsrfProtection = true

