[ui]
# Hide the menu and footer
hideTopBar = false
hideSidebarNav = false

[browser]
# Don't gather usage stats
gatherUsageStats = false

[server]
# Server configuration
enableCORS = false
enableXsrfProtection = true

